### ISSUE TITLE
Editor crashes when PIE with 2 players

### ISSUE THREAD

**Issue by JernejHabjan** [npruehs/ue4-rts#102]
Hi!

I've cloned your repository and switched to 'release/1.0' branch and started editor.
I tried opening SKM-DarkSpace in PIE and it worked fine.
Then I tried running same map, but with 2 players to play in editor, where crash occurred.
It opened 2 windows, but then editor crashed.

I can append end of RTSProject.log when crash occurred, but it doesn't say much.

```
Bringing World /Game/Maps/UEDPIE_2_SKM-DarkSpace.SKM-DarkSpace up for play (max tick rate 60) at 2019.04.19-09.30.12
LogWorld: Bringing up level for play took: 0.001292
LogLoad: Took 0.056221 seconds to LoadMap(/Game/Maps/UEDPIE_1_SKM-DarkSpace)
LogNet: Client netspeed is 10000
LogNet: Join request: /Engine/Maps/Entry?Name=JernejHabjan-6E3546DB48641B308E3A8B89732E80AC?SplitscreenCount=1
LogOnlineSession: Warning: OSS: No game present to join for session (GameSession)
LogOutputDevice: Warning: 
Script Stack (1 frames):
GameModeBase.InitializeHUDForPlayer

LogWindows: Windows GetLastError: The operation completed successfully. (0)
```

I hope this helps to solve the crash.

Also, I would be willing to contribute to this project of yours if you need any extra hands. It would be nice if you could point me in direction that needs to be fixed/implemented. Oh and issues would need some more description, so I could see exactly what do you mean by that feature.

Anyway, great work!

**Comment by npruehs** [comment]
Thanks for reporting! Fixed in commit fdcb8ae4b3810b5a9c4dbae00084404815845797.

Sorry, I'm quite busy right now leading the team making A Year Of Rain based on this plugin, and we've got a major milestone ahead. I'd be happy to extend the descriptions afterwards :)
