### ISSUE TITLE
Is it possible to setup a grid for building placement?

### ISSUE THREAD

**Issue by Andrene** [npruehs/ue4-rts#104]
I was wondering if there is a way to make building placement grid based like SC2

**Comment by npruehs** [comment]
Hey @Andrene !

Sorry for the late reply - this one must have somehow slipped through.

Yes, that is definitely possible, and we did exactly that for A Year Of Rain. All you need to do is modify `ARTSPlayerController::PlayerTick`, which currently just does

`BuildingCursor->SetActorLocation(HoveredWorldPosition);`

In A Year Of Rain, we modified that code to something along the lines of

```
FVector NewBuildingCursorLocation = URTSUtilities::GetGroundLocation(this, HoveredWorldPosition);

// Snap to grid.
NewBuildingCursorLocation = URTSUtilities::ConvertWorldToBuildingGridLocation(this, NewBuildingCursorLocation);

BuildingCursor->SetActorLocation(NewBuildingCursorLocation);
```

While it seems like `GetGroundLocation` is already available here, I don't think `ConvertWorldToBuildingGridLocation` is, but I'm happy to share it with you. Luckily, Unreal Engine does already provide `FMath::GridSnap`, which is exactly what we're looking for here. We store our grid cell size in our game instance to be shared across all game modes, but you can put it anywhere you like (could even be just a constant). The resulting code might look similar to this:

```
FVector URTSUtilities::ConvertWorldToBuildingGridLocation(UObject* WorldContextObject, const FVector& WorldPosition)
{
    URTSGameInstance* GameInstance = Cast<URTSGameInstance>(UGameplayStatics::GetGameInstance(WorldContextObject));

    if (GameInstance == nullptr)
    {
        return WorldPosition;
    }

    float BuildingGridTileSize = GameInstance->GetBuildingGridTileSize();
    FVector NewBuildingCursorLocation = WorldPosition;

    if (BuildingGridTileSize > 0.0f)
    {
        NewBuildingCursorLocation.X = FMath::GridSnap(NewBuildingCursorLocation.X, BuildingGridTileSize);
        NewBuildingCursorLocation.Y = FMath::GridSnap(NewBuildingCursorLocation.Y, BuildingGridTileSize);
    }

    return NewBuildingCursorLocation;
}
```

Hope that helps!

**Comment by Andrene** [comment]
When attempting to build VS gives an error of URTSGameInstance: undeclared identifier.

**Comment by npruehs** [comment]
Hey @Andrene! Looks like we're missing an include somewhere - can you post the full error message?

**Comment by npruehs** [comment]
I'm closing this now for tracking purposes. Feel free to re-open in case you've still got any questions!
