### ISSUE TITLE
Set pawn AI controller class to your RTSCharacterAIController

### ISSUE THREAD

**Issue by FekkakaVolrod** [npruehs/ue4-rts#105]
Hi im new and i dont speak a lot english, how i can "Set pawn AI controller class to your RTSCharacterAIController", i dont find PAWN AI CONTROLLER in the class setting.
Ty if you can help me

**Comment by npruehs** [comment]
Hey @FekkakaVolrod !

Sorry for the delay. I was referring to the "AI Controller Class" property in the "Pawn" category of your character blueprint.

So, after opening any blueprint of type Pawn or Character, in the details panel, look for the AI Controller Class property in the Pawn section.

I've added a screenshot for clarification.

Hope that helps!
Nick

![AIControllerClass](https://user-images.githubusercontent.com/757321/70442892-71367680-1a97-11ea-8947-caba09b8b34d.png)

**Comment by npruehs** [comment]
I'm closing this now for tracking purposes. Feel free to re-open in case you've still got any questions!
