### ISSUE TITLE
Units not moving

### ISSUE THREAD

**Issue by JaredP94** [npruehs/ue4-rts#108]
Hi @npruehs,

I've been following your work for some time and decided to take a stab at using your plugin (release branch). Big fan of the work you've been doing here :)

I've been working through your usage guide (specifically the units component) and upon reaching the order binding section for smart orders, I've noticed that units are not moving when given orders. 

I've created a unit derived from RTSCharacter with all relevant components (Character Movement component added by default).

Please feel free to request any additional information if needed :)

Thanks!

**Comment by JaredP94** [comment]
I've been testing your demo project to look for inconsistencies with my own project.

1. I noticed that you spawn a unit on the player start location, where do you manage the logic for that? 

2. If I add another unit into your level and set it's team index to match the spawned unit, I find it's selectable but does not move on order (similar to what I'm experiencing in my game).

Hope this helps in making the problem clearer :)

**Comment by JaredP94** [comment]
Hi @npruehs,

Just a quick update, I've managed to reproduce unit movement on a unit derived from the RTSPawn class. Still unable to reproduce movement for a unit derived from the RTSCharacter class.

**Comment by npruehs** [comment]
Hey @JaredP94 !

Thanks for the warm words :)

Just to be sure that we're on the same page:

1. In the demo project, does movement work there?
2. Have you generated the navigation mesh for your level, and verified it looks as expected?
3. Is the log showing any warnings or errors?

**Comment by JaredP94** [comment]
Hi @npruehs,

Sorry, I meant to update this issue earlier. I noticed the logs weren't outputting any "Ordered Actor" messages when issuing commands to the RTSCharacter unit. That led me to realise that it was being controlled by the incorrect AI Controller. After that, all worked as expected!

Hope you didn't spend much time looking into this in the interim :)

Keep up the great work!
