### ISSUE TITLE
Where is value of SelfActor blackboard key set?

### ISSUE THREAD

**Issue by JaredP94** [npruehs/ue4-rts#112]
Hi @npruehs,

Currently working on updating your plugin to support 4.25 as it brings a lot of useful features that can improve the AI component of the plugin.

Upgrading the project target seems to have resulted in the **SelfActor** key of the blackboard always returning a null value. I'm trying to determine where we set the value of this key but I haven't had any success.

Please could you provide some clarity on how that is done?

Thanks!

**Comment by npruehs** [comment]
Hey @JaredP94!

SelfActor was never set by the plugin explicitly; I assume the engine does (did?) do so itself.

**Comment by JaredP94** [comment]
Thanks for the speedy response @npruehs!

Makes sense why I couldn't find any references :) 

I haven't seen any mention in the release notes that mentions this change, but I'll bring it up on the forums.

In the interim, a valid solution is to do a cast on the **Owning Actor** input to get the controlled pawn, which achieves the same goal. I imagine this simply does the work that the engine was previously doing in the background to populate the value of **SelfActor** key.

![image](https://user-images.githubusercontent.com/13906915/81122310-f0d64d80-8f30-11ea-90a1-e56b8c63ae7c.png)

**Comment by JaredP94** [comment]
Just a final update, forums have resulted in feedback that general practice is to cast to AI controller and get the controlled pawn instead of using SelfActor. Will propagate that through affected decorators and tasks for 4.25 support.
