### ISSUE TITLE
Option to include this plugin as submodule/downloadable plugin in git

### ISSUE THREAD

**Issue by JernejHabjan** [npruehs/ue4-rts#114]
Hey,

Is there an option, to include this plugin in git repository as submodule?
I cannot declare submodule, because this whole repository includes also other files, which are not related to plugin itself

**Comment by npruehs** [comment]
Hey @JernejHabjan!

I'm not aware of any options for including just subfolders in Git as submodules. I did some digging, and there's workarounds such as [including the whole repo and using symlinks](https://stackoverflow.com/a/5303867/1700174) to the plugin folder, which isn't great but should work in your case.

**Comment by JernejHabjan** [comment]
Can I maybe initialize whole repository as a submodule and set RTS plugin path in build script?

**Comment by JernejHabjan** [comment]
Is there a possibility that RTSProject/Plugins/RealTimeStrategy folder gets pushed to another repository and is used in this one as a git submodule?
This would make it so much easier as I could then also initialize a git submodule of my own?

**Comment by npruehs** [comment]
Hey @JernejHabjan ,

yeah, that should work. It would require some re-thinking of where to put what in terms of documentation.

"Unfortunately", I've just become a father and I don't have the time to do that right now, but I'll definitely keep that in mind!

**Comment by JernejHabjan** [comment]
Hey @npruehs congratulations!

Oh and I managed to get it to work with symlink as you recommended (still a proper submodule would be welcome as well).

Thanks and have a good one.
