### ISSUE TITLE
Cannot open RTSProject.uproject due to missing or outdated modules.

### ISSUE THREAD

**Issue by PanzerVIIPrommy** [npruehs/ue4-rts#123]
Trying to open the RTSProject.uproject comes with the error "Missing RTSProject Modules" and lists the following modules as either missing or built with a different engine version:

RTSProject
RealTimeStrategy
DaedalicTestAutomationPlugin
DaedalicTestAutomationPluginEditor.

Trying to rebuild them only comes with the error "Cannot be compiled. Try rebuilding from source manually".

**Comment by npruehs** [comment]
Hey @PanzerVIIPrommy !

Where have you downloaded the project? Was that a GitHub branch or an official release version?

In general, you'll have to compile the binaries yourself (using Visual Studio) when opening the example project. Currently, that project is targeted at Unreal Engine 4.25.

Official releases contain just the plugin, but with precompiled binaries as stated in the download (e.g. RealTimeStrategy-1.2.0-Windows-UE4_4.25.zip can only be used in Unreal Engine 4.25). These releases can be used in blueprint projects as well.

**Comment by PanzerVIIPrommy** [comment]
Good day!

I downloaded it from the latest GitHub branch, specifically the 1.2.0 release. Filename is "ue4-rts-1.2.0.zip". 

Just to be clear, I have to compile the binaries  of the project? If so, may I have know how to compile them so that they work with my Unreal Engine version (v 4.25)?

**Comment by npruehs** [comment]
Hey @PanzerVIIPrommy!

Yes, if you're pulling (or downloading) from Git, then you'd have to compile the binaries yourself.

However, you can always access the latest release from the [releases page](https://github.com/npruehs/ue4-rts/releases), which includes pre-compiled binaries.

Best regards,
Nick

**Comment by npruehs** [comment]
Hey @PanzerVIIPrommy!

Yes, if you're pulling (or downloading) from Git, then you'd have to compile the binaries yourself.

However, you can always access the latest release from the [releases page](https://github.com/npruehs/ue4-rts/releases), which includes pre-compiled binaries.

Best regards,
Nick

**Comment by npruehs** [comment]
Hey @PanzerVIIPrommy!

Yes, if you're pulling (or downloading) from Git, then you'd have to compile the binaries yourself.

However, you can always access the latest release from the [releases page](https://github.com/npruehs/ue4-rts/releases), which includes pre-compiled binaries.

Best regards,
Nick

**Comment by npruehs** [comment]
I'm closing this now, for tracking purposes. Feel free to re-open in case you've got any follow-up questions!
