### ISSUE TITLE
characters not moving

### ISSUE THREAD

**Issue by jacopomaroli** [npruehs/ue4-rts#124]
Hi there, I'm having an issue with making my characters (**I'm not using pawns**) move on RMB click.
I compiled the project example you provided and it works fine. The one I built from scratch following your manual had issues around [here](https://github.com/npruehs/ue4-rts/blob/develop/Source/RTSProject/Plugins/RealTimeStrategy/Source/RealTimeStrategy/Private/RTSPlayerController.cpp#L310)
All my characters are placed by hand on the map. So I simply "set owner" of a specifc class to my player controller on "begin play" in the playercontroller BP just to get going. (I could have used the RTSOwner property but I wanted to play safe since I don't know where the issue really is)
As you can see from the logfile I attached, the actors gets selected correctly so my suspicions are around that `LogRTS: Warning: Failed to set up blackboard for AI RTSPlayerAIController_0.`
To exclude any navmesh issue I also made a simple script which makes one of the characters walk between two waypoints over and over with `simple move to location` and it works as expected.
I probably have to mention my models are insects and they're scaled accordingly (We're talking about 20x10x10 in game units).
I’m also fairly sure the order itself gets issued because when debugging step by step in visual studio bSuccess [here](https://github.com/npruehs/ue4-rts/blob/develop/Source/RTSProject/Plugins/RealTimeStrategy/Source/RealTimeStrategy/Private/RTSPlayerController.cpp#L345) is true

Here are the logs
```
LogTemp: Repeating last play command: Selected Viewport
LogPlayLevel: PlayLevel: No blueprints needed recompiling
PIE: New page: PIE session: WIP (5 Aug 2020, 22:51:28)
LogPlayLevel: Creating play world package: /Game/Maps/UEDPIE_0_WIP
LogPlayLevel: PIE: StaticDuplicateObject took: (0.011037s)
LogAIModule: Creating AISystem for world WIP
LogAISub: UAISubsystem::UAISubsystem EnvQueryManager (000001F5C6283E00), frame # 40279
LogAISub: UAISubsystem::UAISubsystem AIPerceptionSystem (000001F5B7542AC0), frame # 40279
LogPlayLevel: PIE: World Init took: (0.003140s)
LogPlayLevel: PIE: Created PIE world by copying editor world from /Game/Maps/WIP.WIP to /Game/Maps/UEDPIE_0_WIP.WIP (0.014997s)
LogUObjectHash: Compacting FUObjectHashTables data took   4.12ms
LogAudioMixer: Display: Audio Mixer Platform Settings:
LogAudioMixer: Display:     Sample Rate:                          48000
LogAudioMixer: Display:     Callback Buffer Frame Size Requested: 1024
LogAudioMixer: Display:     Callback Buffer Frame Size To Use:    1024
LogAudioMixer: Display:     Number of buffers to queue:           2
LogAudioMixer: Display:     Max Channels (voices):                32
LogAudioMixer: Display:     Number of Async Source Workers:       0
LogAudio: Display: AudioDevice MaxSources: 32
LogAudio: Display: Using built-in audio occlusion.
LogAudioMixer: Display: Initializing audio mixer.
LogAudioMixer: Display: 0: FrontLeft
LogAudioMixer: Display: 1: FrontRight
LogAudioMixer: Display: Using Audio Device Speakers (Cirrus Logic CS4206B (AB 39))
LogAudioMixer: Display: Initializing Sound Submixes...
LogAudioMixer: Display: Creating Master Submix 'MasterSubmixDefault'
LogAudioMixer: Display: Creating Master Submix 'MasterReverbSubmixDefault'
LogAudioMixer: Display: Creating Master Submix 'MasterEQSubmixDefault'
LogInit: FAudioDevice initialized.
LogLoad: Game class is 'MainGameMode_C'
LogWorld: Bringing World /Game/Maps/UEDPIE_0_WIP.WIP up for play (max tick rate 60) at 2020.08.05-21.51.28
LogRTS: Set up team RTSTeamInfo_0 (team index 0).
LogRTS: Set up team RTSTeamInfo_1 (team index 1).
LogWorld: Bringing up level for play took: 0.016397
LogOnline: OSS: Creating online subsystem instance for: :Context_42
LogRTS: Player MainPlayerController_C_0 set up player state MainPlayerState_C_0 ().
LogRTS: Start spot MainPlayerStart_2 is now occupied by player MainPlayerController_C_0.
LogRTS: Player MainPlayerState_C_0 added to team 0.
LogRTS: Spawned wasp_character_C_0 for player MainPlayerController_C_0 at X=-20.000 Y=10.000 Z=125.000.
LogRTS: Player MainPlayerController_C_0 is now owning wasp_character_C_0.
LogRTS: Player MainPlayerController_C_0 is now owning wasp_character_2.
LogRTS: NumAIPlayers = 1
LogRTS: Spawned AI player RTSPlayerAIController_0.
LogRTS: Warning: Failed to set up blackboard for AI RTSPlayerAIController_0.
LogRTS: Start spot MainPlayerStart_2 is now occupied by player RTSPlayerAIController_0.
LogRTS: Player MainPlayerState_C_1 added to team 0.
LogRTS: Spawned wasp_character_C_1 for player RTSPlayerAIController_0 at X=-20.000 Y=10.000 Z=125.000.
LogRTS: Player RTSPlayerAIController_0 is now owning wasp_character_C_1.
LogRTS: Player RTSPlayerAIController_0 is now owning wasp_character2_2.
Cmd: ENABLEALLSCREENMESSAGES
LogEngine: Onscreen warngins/messages are now ENABLED
LogRTS: Using local player state MainPlayerState_C_0.
LogRTS: RTSVisionVolume_1 has 256 tiles of world size 1.953125.
LogRTS: Set up RTSVisionInfo_0 with RTSVisionVolume_1.
LogRTS: Using local vision info RTSVisionInfo_0.
LogRTS: Set up RTSVisionInfo_1 with RTSVisionVolume_1.
PIE: Server logged in
PIE: Play in editor total start time 4.069 seconds.
LogTemp: Resetting audio stream to device id 
LogAudioMixer: Display: 0: FrontLeft
LogAudioMixer: Display: 1: FrontRight
LogTemp: Resetting audio stream to device id 
LogAudioMixer: Display: 0: FrontLeft
LogAudioMixer: Display: 1: FrontRight
LogRTS: Selected actor wasp_character_2.
LogRTS: Selected actor wasp_character2_2.
LogRTS: Selected actor wasp_character3_5.
LogRTS: Selected actor wasp_character_C_0.
LogRTS: Selected actor wasp_character_C_1.
LogBlueprintUserMessages: [MainPlayerController_C_0] Wasp_1
LogBlueprintUserMessages: [MainPlayerController_C_0] Wasp_2
LogBlueprintUserMessages: [MainPlayerController_C_0] Wasp_3
LogBlueprintUserMessages: [MainPlayerController_C_0] Wasp_4
LogBlueprintUserMessages: [MainPlayerController_C_0] Wasp_0
```

Thanks and keep up the good work!

**Comment by jacopomaroli** [comment]
ok I solved it. There were several issues at play:
1) For both Pawn BP and Character BP In Class Defaults -> Pawn -> AI controller Class I was linking the RTSPlayerAIController definition instead of the BP implementation
2) When launching the project in debug mode from visual studio I noticed I was hitting a lot of INT 3 breakpoints when it was attempting to load game tags. as I added games tags as per [here](https://github.com/npruehs/ue4-rts/blob/0f30666b3f9208b78f265fc8761b432cdbcda340/Documents/Manual/Setup.md#gameplay-tags) I was able to issue move orders correctly... **almost** which leads us to...
3) the characters were always moving down so I placed a debug sphere on every target location on move order (player controller -> Event OnIssuedMoveOrder -> draw debug sphere -> print string) and I noticed the sphere always had the same size and target coordinates were strange. I resized the RTSCameraBoundsVolume on the Z axis and made it thinner. Units started to move correctly, problem is now I cannot move the camera anymore as it's outside the cube. I made the cube tall again thinking I'd incour in the weird issue again but no! I can now move camera and issue move order correctly

It's been tough but I learned few insights and caveats worth sharing and maybe updating the Setup.md to put more emphasis around the tags being necessary to obtain a minimum viable demo project

**Comment by npruehs** [comment]
Thanks for bringing this up! I think there's enough emphasis on the gameplay tags setup, but I'm still glad you found the issue.

Your movement issues seem similar to the ones mentioned in #149, so we could continue the discussion there.

I'm closing this now, for tracking purposes. Feel free to re-open in case you've got any follow-up questions!
