### ISSUE TITLE
How to setup Behavior Tree?

### ISSUE THREAD

**Issue by officefish** [npruehs/ue4-rts#129]
I don't see any ability to create new BluePrint instance of BT_RTSPawnBehaviorTree. What exactly I need to do for set BehaviorTree? Import it manually from repository? Could you please explain step by step what i should do?

**Comment by officefish** [comment]
I manually copy both this uassets from Content folder of Plugin to Content folder of project and now both this classes can be used to set it in AIController. Is it okay ?!

**Comment by npruehs** [comment]
Hey @officefish !

Sure, if that works for you. Usually, you should be able to use the classes by enabling "Show Plugin Content" in the View Options of your Content Browser.

![ShowPluginContent](https://user-images.githubusercontent.com/757321/93377792-c8a21800-f85b-11ea-8ace-7c882cf2b69a.png)

**Comment by npruehs** [comment]
I'm closing this now, for tracking purposes. Feel free to re-open in case you've got any follow-up questions!
