### ISSUE TITLE
Camera and unit movement issue

### ISSUE THREAD

**Issue by coolyoshi** [npruehs/ue4-rts#131]
Hey there,

Really really love this rts plugin, just been struggling getting the camera and unit movement to work.

I've followed the manual and set up everything (except for UI and AI), but for some reason my camera won't move when I press the arrow keys. Other inputs such as mouse scrolling or unit group saving works however.

The second issue is my units won't move. From debugging I can see the move command gets fired off but unit just stays there.

Some info: I've checked navigation with P and it looks all good. I'm using landscape as well

Anyone know what could be wrong or what components I should look at?

Thank you!

**Comment by coolyoshi** [comment]
Okay I've fixed camera issue, I didn't properly set the brush size for camera bounds, still struggling with unit movement issue

**Comment by coolyoshi** [comment]
After countless hours, finally found the issue (If only I didn't ignore those visual studio errors when debugging).
The [documentation ](https://github.com/npruehs/ue4-rts/blob/develop/Documents/Manual/Setup.md) says to add the tag "DT_RTSGameplayTags", but actually we need to add the tags defined in RTSGameplayTagLibrary.cpp. Imo if you're a total noob I think the documentation can be a bit misleading.

**Comment by coolyoshi** [comment]
see comments above

**Comment by npruehs** [comment]
Hey @coolyoshi ,

the documentation is correct and tells you to add the DT_RTSGameplayTags asset to the Gameplay Tag Table List. That asset adds all gameplay tags required for the plugin. You might need to enable "Show Plugin Content" to be able to do so.
