### ISSUE TITLE
Fog Of War - Change outside field of vision to dark instead of gray

### ISSUE THREAD

**Issue by coolyoshi** [npruehs/ue4-rts#134]
I think it would be useful to have an option to change the fog of war to something similar to Warcraft 3 where areas outside field of vision are just slightly darker:

![fogofwargoals](https://user-images.githubusercontent.com/5431677/94339377-73c67600-ffae-11ea-896d-dab6f0b74e75.png)

Or if anyone knows how to implement this any help would be greatly appreciated

**Comment by Zimbo1786** [comment]
Hi @coolyoshi ,

This can be done through C++ in the RTSFogofWar.cpp in this section:

			case EStratVisionState::VISION_Known:
				FogOfWarTextureBuffer[iBlue] = 0;
				FogOfWarTextureBuffer[iGreen] = 255;  ----- this line you can change to darken the known fog. Say 110.
				FogOfWarTextureBuffer[iRed] = 0;
				FogOfWarTextureBuffer[iAlpha] = 0;
				break;

It could probably also be done in the Fog of War material in the UE4 editor, but I preferred through C++.

Hope that helps.

**Comment by coolyoshi** [comment]
@Zimbo1786 

That did the trick, you actually saved me.
Edited the value in C++ and it looks perfect.

Thanks so much for the help

**Comment by Zimbo1786** [comment]
No worries @coolyoshi - glad to have been able to help out.

**Comment by npruehs** [comment]
This should already be part of the plugin; there are three different vision states:

- VISIBLE - normal color
- KNOWN - desaturated
- UNKNOWN - full black
