### ISSUE TITLE
Multiple selection sounds

### ISSUE THREAD

**Issue by JernejHabjan** [npruehs/ue4-rts#137]
Now we can assign only 1 selected sound to RtsSelectableComponent.

We could make it like SC2/ Warcraft where multiple sounds are bound and we cycle through them at random

**Comment by Zimbo1786** [comment]
Hi @JernejHabjan and @npruehs,

This can be done by:
- Importing the sounds into UE4
- Create a sound cue
- Add a random node in the Sound Cue and add more input pins as needed
- Connect the random node to the output node
- Add a wave player and left-click on it to select it. You can then choose your desired sound from the drop-option on the sound wave.
- Repeat for as many pins you have
- Connect the wave player nodes to the random node
- Add this cue to the RTSSelectableComponent for your character / pawn

**Comment by npruehs** [comment]
Hey @Zimbo1786 ,

thanks for your detailed explanation!

Actually, that's what I had in mind originally, but when I saw this issue, I completely forgot about that :)

Cheers!
Nick

**Comment by Zimbo1786** [comment]
Hi @npruehs,

No worries, happy to help out with the explanation. 

Makes sense with the cycling of sounds!
