### ISSUE TITLE
Game time / speedup/ slowdown/ pause

### ISSUE THREAD

**Issue by JernejHabjan** [npruehs/ue4-rts#138]
For example Settlers

**Comment by npruehs** [comment]
Unreal Engine should already have these - check 

https://docs.unrealengine.com/en-US/BlueprintAPI/Utilities/Time/SetGlobalTimeDilation/index.html
https://docs.unrealengine.com/en-US/BlueprintAPI/Game/SetGamePaused/index.html

for instance.

**Comment by npruehs** [comment]
I'm closing this now, for tracking purposes. Feel free to re-open in case you've got any follow-up questions!
