### ISSUE TITLE
Upgrading mining amounts/possible workarounds.

### ISSUE THREAD

**Issue by Andrene** [npruehs/ue4-rts#140]
I've been trying to figure out some way to have it possible to increase mining amount, and if thats not possible then on resource returned add a number of resources depending on the resource and upgrade level. It looks like increasing the mining amount isn't possible, and just adding resources on resource returned may be possible.

I've tried using the built in Add Resources function, however its asking for a target of RTSPlayer Resources Component, which when I get it within the BP_RTSPlayerController it gives an error of 'RTSPlayerController.PlayerResourcesComponent is not blueprint visible. Please fix markup or cease accessing as this will be made an error in a future release.' Is there any solution to this/a reason why PlayerResourcesComponent isn't Blueprint visible/a better way?

**Comment by npruehs** [comment]
Hey @Andrene !
You should always be able to just do a "Get Component Of Class" node to access that component?

**Comment by Andrene** [comment]
Alright, that seemed to work! Forgot about that function, although now that it works its created another problem, but I should be able to resolve that.
