### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by coolyoshi** [npruehs/ue4-rts#145]
@npruehs

Just wondering if you might be interested in setting up a discord server? I'm finding the main ue4 discord server too generic and sometimes it's hard to get help with so many other people asking questions. Feel like it would be cool to create one specifically for Unreal RTS development. I could help set it up if needed as well

**Comment by aqua-pro** [comment]
I'd love a discord!

However, I don't think everything should be done in discord. Many of the solutions presented in tickets have been useful to me, and I feel like discord's information is temporal. So I think we should regularly update the wiki as well 😄

**Comment by coolyoshi** [comment]
Well I think discord does have a pretty decent search feature, but I agree that we shouldn't just solely depend on discord

**Comment by npruehs** [comment]
I believe @coolyoshi set up a Discord, so feel free to ask him to invite you :)

I'm closing this now, for tracking purposes. Feel free to re-open in case you've got any follow-up questions!

**Comment by RM6SS62** [comment]
Is the discord channel active @coolyoshi ?
If so I'd like to get and invite, thanks!

**Comment by coolyoshi** [comment]
> Is the discord channel active @coolyoshi ? If so I'd like to get and invite, thanks!

It's not very active but here it is anyways: https://discord.gg/Jeca7vjnVT
