### ISSUE TITLE
Question regarding movement

### ISSUE THREAD

**Issue by Andrene** [npruehs/ue4-rts#151]
This may be a stupid question, but I started up a new project and did the setup, and tried creating a unit and testing movement. Some questions:
1. For some reason when my unit is spawned by the RTSPlayerStart(my own subclass version) the unit selects just fine but cant move.
2. When I manually create a unit and set its owner component to be owned by index 0(what I'm pretty sure is me) it doesnt let me walk him around on a landscape. Are landscapes incompatible with movement? Making the world one massive plane also doesnt seem to work...
3. I have some blueprints placed on the map(probably will replace them eventually, they are just placeholders for now) but if I right click on one it runs towards the center of the blueprint, and Im guessing its in someway related to question 2.

Any help would be appreciated!

**Comment by coolyoshi** [comment]
Hey there, it's not a dumb question. Also ran into the same issue at the start.

First thing I would double check for is if you setup the tags correctly. Make sure to import the tags file "DT_RTSGameplayTags". Note that isn't the name of a new tag but an actual file you need to import.

Secondly using a landscape is totally okay. If the above doesn't fix the issue, I would also check if you have any custom components sitting between the sky and the landscape as those might interfere with movement orders.

**Comment by Andrene** [comment]
Looks like there was a few of the left over starter actors left over which were causing the issues, so I can move the pre-placed pawn now, although I can't move my spawned pawn yet, not sure exactly whats causing that yet, but It's likely a simple error on my part.

**Comment by coolyoshi** [comment]
I see good to know you got it working! Not too sure either about the spawned pawn issue, but yeah it's probably something small.

**Comment by npruehs** [comment]
Glad you've been able to each other! :) Does your pawn have its AI Controller set to possess on both pre-placed & spawned?

**Comment by Andrene** [comment]
Ah, yep that was it, Auto Possess AI was set to placed in world, changed it to both and alls good. Must've missed that when I was setting up the pawn :p Thanks!
