### ISSUE TITLE
Version 1.2.0 in 4.24.1 states its not compatible and does not load

### ISSUE THREAD

**Issue by Fundati** [npruehs/ue4-rts#152]
I tried importing this plugin into a project in 4.24.1 and the message says:
'The RealTimeStrategy plugin was designed for build 4.25.0. Attempt to load it anyway?'

I click yes, and then it says:
'RealTimeStrategy plugin was built with a different engine version, would you like to rebuild it now?'

I click yes (I'm new to this, not sure if I should or not), it says:
'[Name of project] could not be compiled. Try rebuilding from source manually'

Unreal Engine then shuts down. I'm really new to this game dev stuff and this github says it should be compatible with 4.24

**Comment by coolyoshi** [comment]
It seems it's been updated to 4.26 last month. Also if it says rebuild from source, you can open up the .sln file in visual studio and compile it there.

**Comment by npruehs** [comment]
Hey @Fundati !

Sorry for the confusion about version compatability - I need to get better in communicating which version of the plugin is compatible with which engine version. Blueprints don't make that easier.

Are you using the .zip version of the plugin (e.g. version 1.2.0) or the contents of the Git repository?

**Comment by npruehs** [comment]
Closing this now for tracking purposes. Feel free to re-open in case you've got an update!
