### ISSUE TITLE
Missing details in manual - Relationship.Visible

### ISSUE THREAD

**Issue by ScanTpede** [npruehs/ue4-rts#154]
Hi, it is me again. 
I am here to report missing important description on the manual. Tag Relationship.Visible has to be added to make characters attack each other and it is not mentioned in the manual. It may be intuitive and common sense, but I suffered 2 days trying to find why my characters are not fighting each other. Or it is just me being dumb. Could you add them on the manual to prevent future suffering?

**Comment by Andrene** [comment]
Uhhh, did you not add the RTSVisible component to the unit? I believe that handles the Visible gameplay tag.

**Comment by ScanTpede** [comment]
I already solved the case. It is just a suggestion. Or do you mean Relationship.Visible tag adds automatically if I add RTSVisible component?
