### ISSUE TITLE
'Actor': is not a member of 'FHitResult' when trying to compile in UE5EA

### ISSUE THREAD

**Issue by RM6SS62** [npruehs/ue4-rts#160]
I get a bunch of these:

```...
2>Building 5 actions with 12 processes...
2>  [1/5] Module.RealTimeStrategy.cpp
2>D:/UE4 Projects/Vikings/Plugins/RealTimeStrategy/Source/RealTimeStrategy/Private/Libraries/RTSCollisionLibrary.cpp(148): error C2039: 'Actor': is not a member of 'FHitResult'
2>  D:\games\Epic Games\UE_5.0EA\Engine\Intermediate\Build\Win64\UnrealEditor\Inc\Engine\ProjectileMovementComponent.generated.h(11): note: see declaration of 'FHitResult'
....
```

**Comment by DEV7163** [comment]
Shouldn't you have different releases for 4.26 and 5EA?

**Comment by npruehs** [comment]
There isn't a release for UE5 yet. Please refer to https://github.com/npruehs/ue4-rts/tree/feature/ue5 for the current plugin version for UE5EA.

**Comment by RM6SS62** [comment]
Thank you, and sorry to bother you again but I'm confused.
At https://github.com/npruehs/ue4-rts/tree/feature/ue5 there is a download link that just point to the 4.25 releases.
I'm unable to see where to get the plugin files for UE5A.
