### ISSUE TITLE
Still cant open the project....

### ISSUE THREAD

**Issue by LegendsofBarcraft** [npruehs/ue4-rts#162]
Hey everybody,

I´d like to take a look at the project, but unfortunately, I cant. When I add the project to the plugins folder, I get the following messages. Please, could you help me out? Its been quite some time and I cant get it to work. I´ve tried searching for the .sln file, but couldnt find it.

https://imgur.com/a/Asn3dOc

**Comment by npruehs** [comment]
Hey @Blacksage-beep,

which version of Unreal Engine are you using (4.25, 4.26, 5)? Are you using the Epic Games Launcher version, or are you compiling from source? Do you have Visual Studio installed? And finally, are you using the source version of the RTS plugin (and if so, from which branch), or are you using one of the releases?

Best regards,
Nick

**Comment by LegendsofBarcraft** [comment]
Hi Nick!

Thanks for the swift reply.

I tried it using 5.0, it didnt let me use it. With 4.25, it loads the plugin normally, but I cant access any content it seems. Maybe I just do not have it set up properly. I am running it from the Epic Games Launcher. I do have Visual Studio installed yes. I do not think I am using source version of the RTS plugin or at least I am not aware of it. I downloaded the latest release.

**Comment by LegendsofBarcraft** [comment]
Also, I forgot to add - in 4.25 "CanContainContent" is enabled, but I cant see the content. UPDATE: Nevermind! Got this one, can see the content now. The other problems still stand unfortunately.

**Comment by npruehs** [comment]
There's no release supporting Unreal Engine 5 yet - you'd have to use the source version of the plugin. I'm glad that you're able to open the project now, and see the content.

Which other problems are you referring to?

**Comment by LegendsofBarcraft** [comment]
> There's no release supporting Unreal Engine 5 yet - you'd have to use the source version of the plugin. I'm glad that you're able to open the project now, and see the content.
> 
> Which other problems are you referring to?

Hi Nik! I´ll look into the source code then. Awesome work by the way :)
