### ISSUE TITLE
Cant move my players

### ISSUE THREAD

**Issue by PabloMonfort** [npruehs/ue4-rts#163]
hi there, nice work , i believe this is great but the only thing i need to figure out why is not moving my units, i have follow all but now i cant figure out why is not moving, after select and move a unit in the black board its show up thats its calling to move order but the guy dosnt move and i cant understand why, i add all so far but cant seems the reason of that dosnt work, navmesh its ok, players controllers pawn ai controller pawn player controller the black board set good , no errors, but player dosnt move :( it has the movement component included in the plugin btw, tested with character movement and neither worked so i dont have other choice to come here to ask help thanks.

**Comment by LegendsofBarcraft** [comment]
Hi there Pablito, did you put them on the map? If so, make sure you get the player index right in the player start on the map cause its set to 255.

**Comment by PabloMonfort** [comment]
> Hi there Pablito, did you put them on the map? If so, make sure you get the player index right in the player start on the map cause its set to 255.

well actually they spawn with the start blueprints, but i tought that player index for player was 0? like isnt like the team? team 0 = player team 1 = ai? i get confusse about this , they spawn and i can select them but i believe they are wrong for some reason they dont move. :*( where i have to set this 255? can you give me a more in deep explaination ? thanks.

**Comment by LegendsofBarcraft** [comment]
Im actually trying to replicate your issue right now and there are two possible explanations: You either did not set up the RTSowner component properly or your navmesh is blocked by something. You set up the RTSOwner component by clicking on the actor and setting it up in the RTSOwner component

**Comment by PabloMonfort** [comment]
do you have discord? so i can screen share to you? i actually check about navmesh and navmesh its ok its full green, unit character dosnt have collision only on capsule component, and it has RTSOwner component too, what particular setting need to be add on RTSOwner? i have check the demo and honestly i cant see where the problem is.

It has rtsowner but what special configurations that components need? coz actually i dont see nothing special on it and already have it attached. where that Player index in player start? i have to set 255 to the player start spawn?

**Comment by Blacksage-beep** [comment]
I do have discord, hmu Blacksage#3777

**Comment by LegendsofBarcraft** [comment]
I was able to replicate the issue Pablo has and was not able to solve it. It looks like the MoveTo from Behaviour does nothing yet gets called?

**Comment by coolyoshi** [comment]
Did you add DT_RTSGameplayTags? Note you shouldn't add a new tag called "DT_RTSGameplayTags" but import the file called "DT_RTSGameplayTags".

Also I remember other people have had the same issue in the past so there might be some helpful info in the closed issues

**Comment by npruehs** [comment]
Hard to tell without taking a look at this. What do you mean by "its calling to move order but the guy dosnt move" and "It looks like the MoveTo from Behaviour does nothing yet gets called" - it the behavior tree node stuck executing, or does it finish immediately?

Are other orders working, e.g. attack or construct?

Any way you can share your project for me to take a look?

**Comment by rauflb14** [comment]
I had a problem with the same issue. In the AI Behavior Tree my TargetActor was the RTSMiniMapVolume and the RTSVisionVolume. I set the Collision Presets of both to NoCollision and my unit moved.

**Comment by npruehs** [comment]
Closing this now for tracking purposes. Feel free to re-open in case you've got an update!
