### ISSUE TITLE
Different Stances for Max Speed movement (Feature request)

### ISSUE THREAD

**Issue by PabloMonfort** [npruehs/ue4-rts#164]
hi there, i would like to know if its possible to make players move in different stances like, prone should force infantry soldiers on my game to be slow, walking should go 200 speed and running should be 400. anyone can give me a hint on this if can be archieved or have a clue if its even possible? thanks.

Brw im new into unreal, i see there are some C++ in backend for movement right? would be nice if we have some more control via blueprints around this coz i actually dont know how to deal with the blackboard :(

**Comment by PabloMonfort** [comment]
i think i figure out the problem so never mind, i see some blackboard tutorials and stuff i think its good now and i figure out from animation blueprint to deal with speed using get velocity and vector length ;)

**Comment by PabloMonfort** [comment]
i think i figure out the problem so never mind, i see some blackboard tutorials and stuff i think its good now and i figure out from animation blueprint to deal with speed using get velocity and vector length ;)

**Comment by npruehs** [comment]
There should also be similar settings in the CharacterMovementComponent.
