### ISSUE TITLE
Support engine versions 4.26 and 4.27

### ISSUE THREAD

**Issue by JetBro22** [npruehs/ue4-rts#165]
Hi. I installed plugin to "Plugin" folders of Engine and keep getting error "The following modules are missing or built with a different engine version". Plugins are enabled for project and plugin appears on editor, but when I enable plugin itself and restart editor I keep getting this error that plugin was built for 4.25.0 version. Updating and changing source files and plugin files doesn't help.

My current Unreal version is 4.26.2 while plugin was build for 4.25.0.

Is there a built version for version for 4.26.2?

Edit: I modified plugin file and set it near project itself, now it says "was built for version 4.26.2" and starts compilling, later stops compilling and suggests building it from source myself. Problem with using and launching is still there. So is there a compatible for 4.26.2 version or can it somehow work on 4.26.2?

**Comment by LegendsofBarcraft** [comment]
There is no build for 4.26 as I am aware Elsa.

You´ll have to either stick to 4.25 or try the plugin in 5.0. The sample project runs on 4.25. 

Make sure you downloaded Visual Studio and try to compile it from source. Please note that when you compile the 5.0 version, the code will run some error. The error issue was raised in the closed issues.

**Comment by JetBro22** [comment]
Ok

**Comment by JetBro22** [comment]
Can it run on 4.25.4?

**Comment by LegendsofBarcraft** [comment]
yes

**Comment by npruehs** [comment]
Clarified in commit fca758365c05b0165d2f9ef28ffecad947a5f95c.
