### ISSUE TITLE
"Couldn't find part of path to [path to object]" when trying to build plugin manually

### ISSUE THREAD

**Issue by JetBro22** [npruehs/ue4-rts#166]
Hi. I am trying to build plugin from ZIP files but keep getting errors, as it turns out there is no content (files, scripts) what compiler needs to build plugin. Examples:

All paths are the same and should lead to the same object but the object does not exist for some reason.

      Couldn't find part of path to "path to asset/script", later:
Failed to copy "path to asset/script" to "path leading to the same object", and later:
BUILD FAILED

Is there a way to solve it or am I downloaded ZIP file wrong?

**Comment by LegendsofBarcraft** [comment]
Hi Elsa! 

How are you doing? I encountered similar issues even though not the same issue.., here´s how my limited knowledge can be of help:

Make sure you have Visual Studio installed THEN compile it from source. Try to compile it from source.

**Comment by JetBro22** [comment]
Hi Blacksage
VS 2019 is installed, VC++ is installed too. 
Exactly when I try to compile it from source it comes with such errors, and when I try to launch it with downloaded plugin version it says that it can't compile during runtime

**Comment by LegendsofBarcraft** [comment]
Then I dont know man. It worked for me.

**Comment by JetBro22** [comment]
I'm compiling it from Command Prompt

**Comment by LegendsofBarcraft** [comment]
Yeah, Im not sure. Im not such an expert. I compiled it from the VS file and it worked so I truly dont know how to help you

**Comment by npruehs** [comment]
Hey @JetBro22 !
What do you mean by "compiling it from Command Prompt"?
Where did you put the plugin in your Unreal project folder structure?

**Comment by npruehs** [comment]
Closing this now for tracking purposes. Feel free to re-open in case you've got an update!
