### ISSUE TITLE
Issue around building placement

### ISSUE THREAD

**Issue by PabloMonfort** [npruehs/ue4-rts#167]
Its seems the building placement its only for sphere shape buildings ? 
I try to switch the sphere for a box collider and dosnt work, the tile  height and width it works really weird for me, and i dont know how to tweak this part and i really wish to fix something around this but dont know how this works, can anyone give me some hint on how this works i mean i dont want to use the grid tile but some box colliders coz my buildings are more box-shaped then sphere-shaped, at this point the only way i found to make them work are lead me to use consume buildings only , and for place buildings with grid tile (and still its kinda awkward for some reason dosnt feel not accurate)

**Comment by npruehs** [comment]
Hey @PabloMonfort ! What do you mean by "and dosnt work"? What kind of issue do you experience with box colliders?

**Comment by npruehs** [comment]
Closing this now for tracking purposes. Feel free to re-open in case you've got an update!
