### ISSUE TITLE
Bug on building feature

### ISSUE THREAD

**Issue by PabloMonfort** [npruehs/ue4-rts#168]
There is a bug to me would be nice if you people tell me if have same bug, try to press build any building then before you put the construction on map go back to the ui and press building and there would be a duplicated transparent building shape that is not cleaning right and i dont know where this object comes from? i really wish to know more about that building transparent and the logic around it, how i can check this? coz i want to fix the bug. thanks.

**Comment by npruehs** [comment]
Hey @PabloMonfort !

Check ARTSPlayerController::BeginBuildingPlacement - it's probably a good idea not to spawn a new building cursor while there's still a valid one. If you got a nice, quick fix, feel free to open a pull request :)

Thanks!
