### ISSUE TITLE
MoveTo order does not react, but order to build a building does.

### ISSUE THREAD

**Issue by LegendsofBarcraft** [npruehs/ue4-rts#169]
I´ve run into this peculiar issue -> units seems to be moving fine on a plane, but if you put in a landscape, the MoveTo orders stop working for some odd reason.

I have tags set up correctly, everything is correct. It has to be some landscape issue since I used the test project as well to see if I can replicate the bug.

If you open the project, replace the plane with a landscape, you will be able to replicate the bug.

Any ideas?

**Comment by coolyoshi** [comment]
That's strange, it should work with landscape. Do you have the latest code? I added a quick fix for one of the causes of movement issues here: https://github.com/npruehs/ue4-rts/commit/1df4991c6ec762110291a0f2d8f9eb4880928139

**Comment by LegendsofBarcraft** [comment]
Im using the 4.25 sample project latest release. I will try to use the additions to the code which you added and see if it works

**Comment by LegendsofBarcraft** [comment]
Btw: could you link the discord as well? :)

**Comment by coolyoshi** [comment]
Sure here it is: https://discord.gg/y8KETu8rVM

**Comment by coolyoshi** [comment]
Another thing you could try is in build menu, click "build paths"

**Comment by LegendsofBarcraft** [comment]
The bug persists even through building paths. Does anybody experience similar issue?

**Comment by npruehs** [comment]
I can't confirm that being an issue, at least in UE5.0.

Here's what I've tried:

- Open SKM-DarkSpace.
- Remove plane.
- Add landscape.
- Confirm paths have been built.
- Observe that units can move as expected.

Initially, they didn't react to move orders - but the landscape was above the units. Make sure landscape Z is set properly, so units are above the landscape, not vice versa.

**Comment by LegendsofBarcraft** [comment]
Hi Nik! I eventually figured it out. The collision of other actors caused it. I had to remove ALL collision from the level and then go one by one and I figured it out :)

**Comment by npruehs** [comment]
Thanks for the update! :)
