### ISSUE TITLE
Min/Max Distances Swapped in Inline Docs

### ISSUE THREAD

**Issue by GuyPaddock** [npruehs/ue4-rts#176]
Not sure if these are the only two that [are swapped](https://github.com/npruehs/ue4-rts/blob/034ff2bd3ccd21df598f29b6226932cd0d5f62ea/Source/RTSProject/Plugins/RealTimeStrategy/Source/RealTimeStrategy/Classes/RTSPlayerController.h#L409), but it looks like the descriptions for `MinCameraDistance` and `MaxCameraDistance` are swapped in `ARTSPlayerController`.

**Comment by npruehs** [comment]
Thanks @GuyPaddock - well observed! Fixed in ea006f497eb0e9be4f0c92950d1cc53bd903b5cd.
