### ISSUE TITLE
IssueMoveOrder vs MoveIntoBlackboardRangeToLocation

### ISSUE THREAD

**Issue by nsticco** [npruehs/ue4-rts#179]
Hello, I was wondering if you could clarify how IssueMoveOrder and MoveIntoBlackboardRangeToLocation are meant to function.

In the example project, I'm able to get a pawn to move by...

1. Assigning it the BP_RTSPawnAIController controller class
2. Assigning BP_RTSPawnAIController a new Behavior Tree with a single sequence
3. Adding RTSBTTask_MoveIntoBlackboardRangeToLocation or the native MoveTo with a Target Location as the only task within that sequence

When I do the same with RTSBTTask_IssueMoveOrder, I see no result. Am I misunderstanding the purpose of IssueMoveOrder or do I have something setup wrong? 

This is using UE5 Preview and the feature/ue5 branch

![IssueMoveOrder](https://user-images.githubusercontent.com/16808547/156288440-161ee9da-0a61-4382-80aa-e52a88809e3d.png)

**Comment by npruehs** [comment]
Hey @nsticco!

You shouldn't need to build your own behavior trees. If you still want to do that, I recommend taking a look at AI/BT_RTSPawnBehaviorTree for reference in the plugin content folder. You might need to enable "Show Plugin Content" in your content browser settings.

Using the node RTSBTTask_IssueMoveOrder without using the default behavior tree shipped with the plugin is deemed to fail, as your own behavior tree doesn't contain any logic for actually carrying out that move order.

**Comment by nsticco** [comment]
Very helpful, thank you for clarifying!

And thank you for all the work you've put into the plugin!
