### ISSUE TITLE
Binary files problem

### ISSUE THREAD

**Issue by ForgottenFrog** [npruehs/ue4-rts#180]
Hi @npruehs 
Thank you for still solving problems for this code and thank you for remaking the AI code!
I hope you don't mind it...but is it possible to get some screenshots from inside the blueprints? I can't open these binary files. The engine version (4.25) doesn't read them. 4.26 can read only the BTService file, but doesn't want to open it, it says it's invalid.
I've been trying to open the files with 4.25, 4.26, 4.27, but I couldn't find a way of making the project fully work... I've even installed the 4.25 source engine version, but with no use...

![image](https://user-images.githubusercontent.com/60656276/156437082-9c0c109a-3a51-4a99-a536-905a3c646591.png)

**Comment by npruehs** [comment]
Looks like I've made a stupid mistake here. I saved these assets with UE5, which apparently isn't backwards-compatible. I'm gonna re-save them with UE 4.27, but I don't have time for that today.

**Comment by ForgottenFrog** [comment]
Thank you! I really appreciate it!

**Comment by npruehs** [comment]
Fixed in commit fca758365c05b0165d2f9ef28ffecad947a5f95c.
