### ISSUE TITLE
Is there a reason RTSPlayerAIController does not use RTSPlayerState?

### ISSUE THREAD

**Issue by nsticco** [npruehs/ue4-rts#196]
Hello, I notice RTSPlayerAIController does not seem to reference RTSPlayerState, while RTSPlayerController does. Is there an advantage / best practice to not using PlayerState with RTSPlayerAIController?

I was planning on adding PlayerState for AI in my game, but I wanted to see if there are pitfalls / downsides I should be aware of.

**Comment by npruehs** [comment]
Hey @nsticco !

I don't see why that shouldn't work. In fact, it might be a good idea to do so, to have access to player index/team index/own actors.

Best regards,
Nick

**Comment by nsticco** [comment]
Thanks!
