### ISSUE TITLE
Fire Projectile

### ISSUE THREAD

**Issue by npruehs** [npruehs/ue4-rts#25]

**Comment by HeadClot** [comment]
Consider object pooling for the raycasts / projectiles for this feature. It will save allot of performance when allot of projectiles are on the screen.

https://www.raywenderlich.com/136091/object-pooling-unity

**Comment by npruehs** [comment]
Added in commit b1b53f386c78d925e5d0942646b2d7ba1a31f92d. Opened #41 for projectile pools.

**Comment by HeadClot** [comment]
Awesome :D
