### ISSUE TITLE
Troop Garrison

### ISSUE THREAD

**Issue by theevil128** [npruehs/ue4-rts#54]
As its say's, meant for buildings, also placed buildings and vehicles like troop carriers.

**Comment by npruehs** [comment]
Actually, that's already there (except for a generic right-click command for entering). I've added this in commit 6f79dd5fbeb7f3a074ac87bb4781167d70df4c9a for construction sites, and it has already been re-used later for resource gathering (e.g. entering gold mines).

**Comment by HeadClot** [comment]
My advice would be make this a component so people can use or not use it as they wish in their project :)

**Comment by npruehs** [comment]
See my linked commit: It already is.

**Comment by HeadClot** [comment]
@npruehs - Got a question about this. Would this work with vehicles such as Aircraft carriers or sea based troop transports?

Just curious :)

**Comment by npruehs** [comment]
Hey @HeadClot! As this is solely based on actors in general, this should work with any kind of unit you can imagine, including vehices, transports, towers, castles, you name it.

**Comment by HeadClot** [comment]
Alright awesome. Thanks for the insight :)
