### ISSUE TITLE
Unable to use plug in

### ISSUE THREAD

**Issue by TaviScipio** [npruehs/ue4-rts#55]
Hello, I've moved this question here from Youtube. I'm having issues getting the plugin to work, though I think that might be an issue with how I'm installing it. How I think it should work is, download the file RTSPlugin and paste it to the Plugins folder in my project file for UE4. ( Unreal Projects > RTSPluginTest > Plugins > My Game Plugin). I created the Plugins folder because there wasn't one there already. Now when I try to launch the project after I've put the RTSPlugin folder in, I get the following message. [https://i.imgur.com/rwrlkqD.jpg](url) When I click No, it loads up to 75% then says "Plugin 'RTSPlugin' failed to load because module 'RTSPlugin' could not be found. Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project."  Now the kicker is that I actually got it to work for a moment, but when I went to enable the plugin and it restarted it gave me the same error message again. 

Thank you, and forgive me if I am making a rookie mistake with this plugin.

**Comment by HeadClot** [comment]
What version of the engine are you using? 

It should work with 4.16.3.

**Comment by TaviScipio** [comment]
I tried using both 4.16.3 and 4.17.1, I got the error on both versions. Should I try uninstalling UE4 and reinstalling?

**Comment by HeadClot** [comment]
>I tried using both 4.16.3 and 4.17.1, I got the error on both versions. Should I try uninstalling UE4 and reinstalling?

I do not think that will solve the issue.

Have you tried compiling the plugin? From what I understand no binaries are provided out of the box for this plugin.

If you have not compiled the plugin here is what you need to do.

1. Create a C++ Project
2. Create a plugins folder in the project directory like you normally do with a BP project.
3. Copy UE4-rts to the plugins folder.
4. Right click the .uproject and generate Visual Studio files. (The exact term escapes me atm)
5. After visual studio loads hit the build button. That should cause it to spit out some DLLs in plugins.

Let me know if this works.

**Comment by TaviScipio** [comment]
I think I found the problem! The SATA connection bent the prongs for my hard drive. I'll have to reinstall UE4 on a new hard drive and I'll let you know if that was the issue! Thanks!

**Comment by npruehs** [comment]
Thanks for pitching in @HeadClot! Let us know whether it works now @TaviScipio :)

**Comment by TaviScipio** [comment]
I started a C++ project and it works! This is an amazing tool y'all and I look forward to using it. I really wish I knew more about coding to help y'all out. I just need to figure out how to setup the components I want! 
Cheers!

**Comment by HeadClot** [comment]
@TaviScipio Awesome to hear that you got it working.
