### ISSUE TITLE
Can't launch project with plugin

### ISSUE THREAD

**Issue by GoIiath** [npruehs/ue4-rts#56]
Hi i've installed the plugin correctly but when i launch my project i have this 
![image](https://user-images.githubusercontent.com/28307393/30660768-458e9e50-9e42-11e7-8c6f-2b2c54ba39a7.png)
and then i got this 
![image](https://user-images.githubusercontent.com/28307393/30660818-6a3a8476-9e42-11e7-8229-f7da98ce5fe5.png)
dunno what to do, so i'm asking here ^^

**Comment by kabivel** [comment]
Same Problem with 17.1 and 16.3

**Comment by HeadClot** [comment]
Hey @GoIiath and @kabivel Check out issue #55 that should help you get started :)
