### ISSUE TITLE
Move order

### ISSUE THREAD

**Issue by GoIiath** [npruehs/ue4-rts#57]
I've got an issue with the move order,
When I right clik on another unit my unit move and attack but when i right click the ground my unit is not moving. 
also can we change the rotate speed when unit have to face the enemy unit ? didn't find anything about that

**Comment by npruehs** [comment]
Hey @GoIiath , have you added a NavMeshBoundsVolume to your level and built navigation? You can You press P to review your results in the viewport.

Everything related to movement and rotation is built-in Unreal stuff, so I recommend checking the CharacterMovementComponent.

**Comment by GoIiath** [comment]
Yeah i've added NavMeshBoundsVolume, I also have the green  ground when I press P,
I'm also using the CharacterMovementComponent, move to attack is working but not simply move

**Comment by npruehs** [comment]
Do you have any ground to actually click on? Movement orders are calculated by casting a ray: If that ray hits a non-enemy collision shape, it will move to the hit location. Otherwise, it will be unable to determine where you actually want to move (it doesn't just cast the ray against a zero-plane or similar).

**Comment by GoIiath** [comment]
Yes I have a ground, i used a cube, it have a "glass" texture also just to be clear, i have to put the RTSplayerStart at the same Z as the green right ?

**Comment by npruehs** [comment]
Hmm, is the cube an actor?

**Comment by GoIiath** [comment]
Nah the cube is just a mesh

**Comment by npruehs** [comment]
Sounds like a bug or wrong setup (= bad documentation ;) ) Is there any way you can share your project?

**Comment by npruehs** [comment]
I will close this for now, please get back to us in case you've got anything new.

**Comment by SyedAman** [comment]
Did you manage to fix this? @GoIiath

**Comment by bbt636** [comment]
I have notice that it doesn't work in a normal mesh but ir does in a brush geometry. I hope this help

**Comment by coolyoshi** [comment]
Having same issue. @bbt636 what do you mean by brush geometry? Did you manage to fix it?

**Comment by LegendsofBarcraft** [comment]
Im having a similar issue when you have an actor on a landscape and issue a MoveTo order. The unit does not react, BUT if you do a construction order the unit reacts. I´ve got navmesh built nicely etc... Any ideas? Its working fine on the Plane in the starter project in regards to movement so its weird
