### ISSUE TITLE
Unit Production Spawn Location and Thanks :)

### ISSUE THREAD

**Issue by cptnight00** [npruehs/ue4-rts#60]
Hi, 

Just want to say I am a huge fan of what you are doing here, and have been playing around, using your exposed values in blue print to add a percentage text render above buildings on their construction. I am not a Programmer however and blueprint is where my talents end.

A bug or more of a feature quest that immediately springs to mind is that there are no rally points for the buildings. Because of that, an unmoved spawned unit will stand next to the building and when another is spawned it will spawn in the same place causing the collisions to fight. 

The offset/world location is also not exposed.
![capture](https://user-images.githubusercontent.com/20490642/36075488-a686966a-0f47-11e8-8b7f-7a13058b5479.JPG)

Thanks Again For your time spent on this, the components method is so much cleaner than other examples I have seen on the unreal marketplace :)

**Comment by npruehs** [comment]
Hey @cptnight00!

Thanks for all the warm words! That's what keeps me going :)

In our current project, we already have rally points in place, and spawning in a circle around the building in case blocked spawn positions as well. I just haven't had the time to merge everything back yet.

**Comment by cptnight00** [comment]
Great to hear! :)

**Comment by npruehs** [comment]
Added rally points in commit eb7f1d231c0bf44e1f5047e8cd7260d325ee6e19.
