### ISSUE TITLE
Not compatible with 4.19

### ISSUE THREAD

**Issue by hankyu1** [npruehs/ue4-rts#63]
Hi! the current develop branch is not compatible with version 4.19.

**Comment by aerenyasar** [comment]
Start a 4.18 project with the plugin and then upgrade it to 4.19.

**Comment by npruehs** [comment]
Hey @hankyu1! Thanks for pointing this out - I'm going to update the plugin in the near future.

Thanks @aerenyasar for pitching in as well! :)

**Comment by aerenyasar** [comment]
@Ancalgonn I didn't check this plugin for a while, I'm working on my own one, so I don't know if there is any progress for updating it to 4.19 (or 4.20).

**Comment by san-smith** [comment]
@Ancalgonn Hi. I had the same problems with version 4.18.3, and I was able to fix them.
Here's what I did:
1) I installed the Visual Studio 2017
2) Using  Visual Studio Installer I added a component "Unreal Engine installer"
3) I launched RTS.uproject from this repositorie and Unreal compiled the plugins.
I hope this helps you.

**Comment by npruehs** [comment]
Project is now fully operational with Unreal Engine 4.18, 19, 20 and 21.
