### ISSUE TITLE
How to set up selection circles?

### ISSUE THREAD

**Issue by npruehs** [npruehs/ue4-rts#64]
Originally posted by Hank Yu at https://www.youtube.com/watch?v=OZWAxdLumXc.

"I was following the instruction on your github. Everything works nicely except for the selection circles. I can't figure out where to listen to the OnSelectionChanged event. Can you help me?﻿"

**Comment by npruehs** [comment]
Hey Hank Yu!

You should be able to get the SelectableComponent of a character and bind to the OnSelected event, if you're interested in a particular actor.

Otherwise, you can create a PlayerController blueprint using RTSPlayerController as base class, and implement OnSelectionChanged there.

Please let me know if that helps!

**Comment by hankyu1** [comment]
Hi Nick!

First of all, thank you for answering my question!
My biggest issue is that for other functionality, I can find the implementation in the example RTS project. But, for selection, I don't see how OnSelectionChanged has been used in RTSSamplePlayerController or RTSSampleCharacter. Can you direct me to where you implement selection circle in the RTS project?

Thank you!

**Comment by npruehs** [comment]
Hey @hankyu1!

In the RTSSampleCharacter blueprint, there's a SelectionCircleDecalComponent that has been added natively by the RTSCharacter class. Currently, the RTSCharacter shows and hides that decal in Tick, based on the current selection state.

In a future iteration, we have moved showing selection circles entirely to the RTSSelectableComponent, and made it entirely event-based, but that somehow didn't make it into the GitHub repo yet.

**Comment by hankyu1** [comment]
I see.
Thank you for your reply. I'll give the new selection circle a try!

**Comment by hankyu1** [comment]
Hi Nice, sorry for the reply.

I was just trying to bind SelectionCircleDecalComponent to RTSSampleCharacter, and I couldn't figure out which method to use to "show" or "hide" the SelectionCircleDecalComponent. Which method do I bind to selection/deselection in RTSSampleCharacter?

**Comment by npruehs** [comment]
Hey @hankyu1, just call SelectActor and DeselectActor on the RTSSelectableComponent. It will handle the selection circles automatically.

**Comment by npruehs** [comment]
I'm closing this now for tracking purposes. Feel free to re-open in case you've still got any questions!
