### ISSUE TITLE
Issue: Selection box does not always select actors

### ISSUE THREAD

**Issue by sovkan** [npruehs/ue4-rts#66]
The selection box does not select units if the player creates the box from any direction except for top left to bottom right. 

Example: the user creates a selection box by clicking and moving the mouse up and right and releases over a unit. The unit will not be selected. However, the unit will be selected if the player moved the mouse down and right.

**Comment by npruehs** [comment]
Yep, that's a known issue I haven't had the time to merge the fix back to GitHub.

Basically, you just have to modify `ARTSPlayerController::GetSelectionFrame` to use the point with the minimum X and Y coordinates first.
