### ISSUE TITLE
Feature request - minimap view frustum clamp

### ISSUE THREAD

**Issue by JernejHabjan** [npruehs/ue4-rts#67]
Feature request 
clamping view frustum for minimap within bounds of widget minimap area.

![image](https://user-images.githubusercontent.com/21958321/40732023-ac01aaea-6432-11e8-9661-eb3545141dec.png)

If camera is tilted, frustum lines go beyond minimap widget, resulting lines being drawn in middle of screen.

**Comment by npruehs** [comment]
Thanks for reporting! :) This should only ever occur with very small maps, so we hadn't  encountered this one yet.

**Comment by josephkozak** [comment]
This was a long time ago; but an easy fix is turning the clipping settings of the widget to "Clip to Bounds" instead of inherit. It helps if you place a border around your mini map as well.

**Comment by npruehs** [comment]
@josephkozak Thanks for the hint!
@JernejHabjan Fixed in commit a683f9d6a9da513fe338ddf9861cfae881017d8c.
