### ISSUE TITLE
Fog of war post processing volume skybox collision

### ISSUE THREAD

**Issue by JernejHabjan** [npruehs/ue4-rts#70]
Hi
I would first like to thank you for this awesome plugin.
I am using your fog of war implementation, but I am getting some weird glitchy skybox when i pan around
[Look at this image](https://prnt.sc/kcbx5d)
Maybe Post proccessing volume is drawing over skybox, but it doesnt fill everything - RTS vision volume (size per tile) is set to 32

**Comment by npruehs** [comment]
Hey @JernejHabjan ! Sorry for the delayed response.

To be completely honest: I've never seen anything like that before :) We've had issues where the total number of tiles isn't a power of two, so we're using pretty weird "size per tile" in our current project, i.e.:

* Map Size (= Vision Volume Extents): 30,000 x 30,000
* Size Per Tile: 117.1875 (which is 30,000 / 256)

But we've never had any issues with the skybox...

Best regards,
Nick

**Comment by npruehs** [comment]
I'm going to close this for now, for tracking purposes. Feel free to reopen if required.

**Comment by JernejHabjan** [comment]
Hey there

reopening this issue, as it is also occurring on SKM-DarkSpace map when adding default BP_SkySphere to map without any other configurations.

![image](https://user-images.githubusercontent.com/21958321/56692613-df822080-66e2-11e9-89b3-8ba13c23f2f6.png)
