### ISSUE TITLE
Editor crashes when a building is active in-game

### ISSUE THREAD

**Issue by charizardfuego52** [npruehs/ue4-rts#72]
Everything is fine, the Plugin works flawlessly... Except for one thing.
Everytime I place a building and click "Play", the Editor crashes. It is really a shame because I wanted to use it... I'm just using the samples and is the sample that crashes. I use UE 4.18.3
PS: anyone has any idea on how can I select one initial character at the start of the game, like a "Hero" selection?
-Thanks!

**Comment by Tdead1** [comment]
Same here.

**Comment by npruehs** [comment]
Can you provide a little more details, e.g. the stack trace of the crash?

How is your building setup, e.g. which base class you using and which components are attached?

**Comment by charizardfuego52** [comment]
It is as simple as downloading the source, opening the sample project (RTS) and placing a building sample. The editor will crash and won't give further details in the crash report. I hope this works

**Comment by npruehs** [comment]
Hey @charizardfuego52 ,

I was unable to reproduce the issue on my side... Here's what I've tried:

- Open RTS.uproject in Unreal 4.18.3.
- Open RTSGameSampleMap.
- Add a single instance of RTSSampleBuilding.
- Hit Play.

However, I've had local changes that I've pushed to the develop branch now.

Would you mind

- telling me which Unreal version you're using
- pulling the most recent changes from the repository, rebuild your project and try again
- if the error persists, attach Saved\Logs\RTS.log immediately after the crash?

**Comment by charizardfuego52** [comment]
Testing tomorrow!

**Comment by charizardfuego52** [comment]
I'll test the changes in a couple of hours, i had to reformat my disks :/

**Comment by charizardfuego52** [comment]
Your changes fixed the problem!, thank you!

**Comment by npruehs** [comment]
That's great to hear :)
