### ISSUE TITLE
Line of Sight

### ISSUE THREAD

**Issue by joakimda** [npruehs/ue4-rts#79]
Feature request for the option of having line of sight with the current fog of war. 

Some kind of line of sight like the following:
https://thumbs.gfycat.com/DisastrousGrandAmericanindianhorse-mobile.mp4

Could it possibly be implemented as a boolean in the vision component and then use line tracing for the vision calculation for actors having the boolean set to true? Maybe do it similar to [this?](http://tongtunggiang.com/blog/2017/12/30/implement-line-sight-unreal-engine-4/) but without creating a mesh and only calculating what tiles are blocked and should not be visible.

**Comment by npruehs** [comment]
Added in commit 9e523aeab30ccd6dbbf4302e808b85335a282078.
