### ISSUE TITLE
Implementation of unit levels and experience.

### ISSUE THREAD

**Issue by charizardfuego52** [npruehs/ue4-rts#80]
I have been trying to implement a Level system where the maximum health of a unit is set to grow when it gets enough exp, but it is not practical and overall doesn't work at all. So I think that the best idea is doing a native solution for this.
Maybe is stupid to ask for this, but is a interesting twist that could be useful for people who wants to do something like WC3 (Btw, it is an excellent game, if you haven't played it, play it) or other RTS.
-Thanks

**Comment by JernejHabjan** [comment]
Hi, Whats your approach to this problem?
Are you setting Actor->RTSHealthComponent->Maximum Health according to current actor level?
I think you could make a child Health component and implement your leveling system in there and then you could just call MyHealthComp->levelUp().
Thats interesting idea though.

**Comment by charizardfuego52** [comment]
Thanks!, this is exactly what i've been searching for!
