### ISSUE TITLE
Drag and drop spawn character in ui

### ISSUE THREAD

**Issue by benyamin-abd** [npruehs/ue4-rts#98]
How i can set drag and drop spawn character in project

**Comment by npruehs** [comment]
Hey @benyamin-abd! I'm afraid I don't fully understand your question - what exactly are you trying to do?

**Comment by npruehs** [comment]
Hey @benyamin-abd !

That sounds more like a general UE4 question. You might want to setup some UMG UI with drag and drop functionality, e.g. buttons with images of your character. Then, you can handle the UI events as usual in Unreal, and spawn the character by deprojecting the mouse location into your world, e.g. against a landscape.

Here are some references to get you started:

https://docs.unrealengine.com/en-us/Engine/UMG/HowTo/DragAndDrop
https://api.unrealengine.com/INT/API/Runtime/Engine/GameFramework/APlayerController/DeprojectScreenPositionToWorld/index.html

I'm going to close this issue now, for tracking purposes, but feel free to re-open it in case you've got any RTS-related questions.

**Comment by npruehs** [comment]
I see. I guess ARTSGameMode::TransferOwnership is what you want.
