### ISSUE TITLE
How to Spawn an Actor and then give an ownership to it?

### ISSUE THREAD

**Issue by rezadarooei** [npruehs/ue4-rts#99]
Hi,

Just want to say I am a huge fan of what you are doing here,and I must say your work is awesome,I have very basic question and I was digging and I cant find any good answer for it,I want spawn an actor then I want character owned it,how it is possible?

**Comment by npruehs** [comment]
Hey @rezadarooei ! Just to be sure I understand the question correctly: What do you mean by "owned", exactly?

**Comment by rezadarooei** [comment]
hi again let's I ask my question step by step.I want to spawn a character or unit in the desired place. second step after it needs to belong one of the team for example client or server? what is the best way to create something like this?
and another question I don't know it is bug or my problem,each time I want to create c++ class it is failed and I need to delete binary folder and regenerate game to see created class.

**Comment by npruehs** [comment]
For spawning units owned by a specific player, you could use ARTSGameMode::SpawnActorForPlayer.

**Comment by npruehs** [comment]
I'm closing this now for tracking purposes. Feel free to re-open in case you've still got any questions!
